dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libboost-test-dev
script:
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T lession1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uvovandro:$BINTRAY_API_KEY https://api.bintray.com/content/vovandro/lession/$TRAVIS_BUILD_NUMBER/lession1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;bt_package=homeword;bt_version=$TRAVIS_BUILD_NUMBER
